// Generated by `pnpm build:moon-runtime` outside this package tree.
// @ts-ignore -- resolved after the MoonBit build step in build/typecheck/test.
import * as generatedMoonBitRuntime from "../../../_build/js/release/build/js/js.js";

export const moonbitRuntime = generatedMoonBitRuntime as Record<string, unknown> & {
  default?: Record<string, unknown>;
};
